user = "postgres.srlisqufztonzfjeocui"
password = "bddbibliothequeperso"
host = "aws-0-eu-west-3.pooler.supabase.com"
port = "6543"
dbname = "postgres"

SUPABASE_URL = "https://srlisqufztonzfjeocui.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybGlzcXVmenRvbnpmamVvY3VpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjgwMTY5MiwiZXhwIjoyMDY4Mzc3NjkyfQ.RtpWWP4gRvn6zF5fPaK2_9DyKKdhiFqqNyFFnkEAejs"